name: Deploy to Streamlit Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test imports
      run: |
        python -c "import streamlit; import PIL; import numpy; print('Basic imports successful')"
    
    - name: Validate app structure
      run: |
        python -c "
        import os
        required_files = ['app.py', 'headshot_generator.py', 'requirements.txt']
        for file in required_files:
            assert os.path.exists(file), f'{file} not found'
        print('All required files present')
        "

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run security checks
      run: |
        pip install safety
        safety check -r requirements.txt || true
